"""wgpu._ffi.structs — Backward-compat shim. Use wgpu._backend.wgpu_native.structs."""

from wgpu._backend.wgpu_native.structs import (
    WGPUStringView, WGPUChainedStruct, WGPUFuture, WGPUFutureWaitInfo,
    WGPUAdapterInfo, WGPUBlendComponent, WGPUBlendState, WGPUColor,
    WGPUExtent3D, WGPUOrigin3D, WGPULimits, WGPUSupportedFeatures,
    WGPUSupportedInstanceFeatures, WGPUSupportedWGSLLanguageFeatures,
    WGPUInstanceLimits, WGPUCompatibilityModeLimits,
    WGPUShaderModuleDescriptorSpirV,
    WGPURenderPassMaxDrawCount, WGPUSurfaceColorManagement,
    WGPUTextureComponentSwizzle, WGPUTextureComponentSwizzleDescriptor,
    WGPUShaderSourceGLSL, WGPUShaderDefine,
    WGPUBufferBindingLayout, WGPUSamplerBindingLayout, WGPUTextureBindingLayout,
    WGPUStorageTextureBindingLayout, WGPUBindGroupLayoutEntry,
    WGPUBindGroupLayoutDescriptor, WGPUBindGroupEntry, WGPUBindGroupDescriptor,
    WGPUBufferDescriptor, WGPUBufferMapCallbackInfo,
    WGPUCommandBufferDescriptor, WGPUCommandEncoderDescriptor,
    WGPUComputePassDescriptor, WGPUComputeState, WGPUComputePipelineDescriptor,
    WGPUConstantEntry, WGPUDeviceDescriptor, WGPUDeviceLostCallbackInfo,
    WGPUUncapturedErrorCallbackInfo, WGPUInstanceDescriptor,
    WGPUMultisampleState, WGPUPassTimestampWrites, WGPUPipelineLayoutDescriptor,
    WGPUPrimitiveState, WGPUQuerySetDescriptor, WGPUQueueDescriptor,
    WGPURenderBundleDescriptor, WGPURenderBundleEncoderDescriptor,
    WGPURenderPassColorAttachment, WGPURenderPassDepthStencilAttachment,
    WGPURenderPassDescriptor, WGPURequestAdapterCallbackInfo,
    WGPURequestDeviceCallbackInfo, WGPURequestAdapterOptions,
    WGPUSamplerDescriptor, WGPUShaderModuleDescriptor,
    WGPUShaderSourceWGSL, WGPUShaderSourceSPIRV,
    WGPUStencilFaceState, WGPUDepthStencilState,
    WGPUSurfaceDescriptor, WGPUSurfaceCapabilities, WGPUSurfaceConfiguration,
    WGPUSurfaceTexture, WGPUSurfaceSourceWaylandSurface, WGPUSurfaceSourceXlibWindow,
    WGPUTexelCopyBufferLayout, WGPUTexelCopyBufferInfo, WGPUTexelCopyTextureInfo,
    WGPUTextureDescriptor, WGPUTextureViewDescriptor,
    WGPUVertexAttribute, WGPUVertexBufferLayout, WGPUVertexState,
    WGPUColorTargetState, WGPUFragmentState, WGPURenderPipelineDescriptor,
    WGPUCompilationMessage, WGPUCompilationInfo,
    WGPUQueueWorkDoneCallbackInfo,
    WGPUPopErrorScopeCallbackInfo,
    WGPUCompilationInfoCallbackInfo,
    WGPUCreateComputePipelineAsyncCallbackInfo,
    WGPUCreateRenderPipelineAsyncCallbackInfo,
    WGPUBorrowedStringView,
    str_to_borrowed_sv, str_to_sv, wgpu_limits_default,
)
