"""wgpu._ffi.types — Backward-compat shim. Use wgpu._backend.wgpu_native.types."""

from wgpu._backend.wgpu_native.types import (
    WGPUAdapterHandle, WGPUBindGroupHandle, WGPUBindGroupLayoutHandle,
    WGPUBufferHandle, WGPUCommandBufferHandle, WGPUCommandEncoderHandle,
    WGPUComputePassEncoderHandle, WGPUComputePipelineHandle, WGPUDeviceHandle,
    WGPUExternalTextureHandle, WGPUInstanceHandle, WGPUPipelineLayoutHandle,
    WGPUQuerySetHandle, WGPUQueueHandle, WGPURenderBundleHandle,
    WGPURenderBundleEncoderHandle, WGPURenderPassEncoderHandle,
    WGPURenderPipelineHandle, WGPUSamplerHandle, WGPUShaderModuleHandle,
    WGPUSurfaceHandle, WGPUTextureHandle, WGPUTextureViewHandle,
    WGPUBool, WGPUFlags,
    WGPU_FALSE, WGPU_TRUE, WGPU_STRLEN, WGPU_WHOLE_SIZE,
    WGPU_ARRAY_LAYER_COUNT_UNDEFINED, WGPU_COPY_STRIDE_UNDEFINED,
    WGPU_MIP_LEVEL_COUNT_UNDEFINED, WGPU_QUERY_SET_INDEX_UNDEFINED,
    WGPU_LIMIT_U32_UNDEFINED, WGPU_LIMIT_U64_UNDEFINED,
    WGPUAdapterType, WGPUAddressMode, WGPUBackendType,
    WGPUBlendFactor, WGPUBlendOperation, WGPUBufferBindingType,
    WGPUBufferMapState, WGPUCallbackMode, WGPUCompareFunction,
    WGPUCompilationMessageType, WGPUComponentSwizzle, WGPUCompositeAlphaMode,
    WGPUCreatePipelineAsyncStatus, WGPUCullMode, WGPUDeviceLostReason,
    WGPUErrorFilter, WGPUErrorType, WGPUFeatureLevel, WGPUFeatureName,
    WGPUFilterMode, WGPUFrontFace, WGPUIndexFormat, WGPUInstanceFeatureName,
    WGPULoadOp, WGPUMapAsyncStatus, WGPUMipmapFilterMode, WGPUOptionalBool,
    WGPUPresentMode, WGPUPrimitiveTopology, WGPUQueryType,
    WGPUQueueWorkDoneStatus, WGPURequestAdapterStatus, WGPURequestDeviceStatus,
    WGPUSamplerBindingType, WGPUStatus, WGPUStencilOperation,
    WGPUStorageTextureAccess, WGPUStoreOp, WGPUSType,
    WGPUSurfaceGetCurrentTextureStatus, WGPUTextureAspect, WGPUTextureDimension,
    WGPUTextureFormat, WGPUTextureSampleType, WGPUTextureViewDimension,
    WGPUToneMappingMode, WGPUVertexFormat, WGPUVertexStepMode,
    WGPUWaitStatus, WGPUWGSLLanguageFeatureName,
    WGPUBufferUsage, WGPUColorWriteMask, WGPUMapMode, WGPUShaderStage, WGPUTextureUsage,
    WGPUCompilationInfoRequestStatus, WGPUPopErrorScopeStatus,
    WGPUPowerPreference,
)
